### ISSUE TITLE
Error when training vignette spls model

### ISSUE THREAD

**Issue by joao-pompeu** [jonathanth/mixOmicsCaret#1]
Hello Jonathan,

First of all, thank you for providing an easier way to integrate PLS from mixOmics in caret package.
I tried to replicate your vignette, however it throws an error when I try to train the model:

Error in filter.default(., ncomp == max(ncomp)) : 
 argument "x" missing, no pattern

My current R version is 4.3.2

**Comment by joao-pompeu** [comment]
Nevermind, I just discovered that it conflicted with the signal package through the filter function.

**Comment by jonathanth** [comment]
Hi Joao! Thanks for trying out the package, let me know if you make something useful with it!
Those pesky function name conflicts are so common in R. I should hardcode the dplyr functions. I will probably do that when I get time to revisit this.
bw j
